### ISSUE TITLE
Experiment property rule has FP for text-decoration

### ISSUE THREAD

**Issue by IGx89** [kalidasya/sonar-css-plugin#1]
The "scss:experimental-property-usage" is flagging "text-decoration: none" as an experimental property in a SCSS file, even though that's valid CSS Level 1 (https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)

**Comment by kalidasya** [comment]
thanks @IGx89 for reporting, I will take a look, is it only triggered in scss files or in css as well?

**Comment by IGx89** [comment]
Just enabled it and tested, yep, css:experimental-property-usage flags on that as well.

**Comment by kalidasya** [comment]
@IGx89 here it says its experimental: https://css-tricks.com/almanac/properties/t/text-decoration/

**Comment by IGx89** [comment]
From that page: 

> All browsers support the CSS2.1 "longhand" property text-decoration. The shorthand property and the sub-properties text-decoration-color, text-decoration-line, and text-decoration-style are supported unprefixed in Firefox, and with the -webkit prefix in Safari. Chrome will also recognize those values with the -webkit prefix and Experimental Web Platforms flag enabled.

The "longhand" form (like text-decoration: underline) is supported by any browser, just the "shorthand" version with subproperties (like text-decoration: underline dotted red) is experimental.

**Comment by kalidasya** [comment]
@IGx89 ok i will look into it, to me it seems by default `text-decoration` is marked as experimental no matter what

**Comment by edwelker** [comment]
+1, text-decoration, in "longhand" form should be fine.  This turns out to be an extremely frequent false-positive.

**Comment by edwelker** [comment]
I can't get the tests to pass locally (for whatever reason), and they don't seem to pass consistently in Travis... so I'm flying a little blind here.  But I've got at least a naive PR together.

**Comment by kalidasya** [comment]
@edwelker so I should not have merged it?

**Comment by edwelker** [comment]
I can't be sure.  It just occurred to me, tho... the repo is now at `kalidasya/sonar-css-plugin`, however the TravisCI build is per `racodond/sonar-css-plugin`, so that's why it didn't run tests for the PR branch (or this current merge).  

This looks like it needs to be setup: https://travis-ci.org/kalidasya/sonar-css-plugin

Looks like this needs a little further infrastructure setup.  I'm willing to help out if needed.  :)

**Comment by edwelker** [comment]
Here's a copy to get the tests running.  

https://travis-ci.org/edwelker/sonar-css-plugin-copy/jobs/280482728

It appears to fail just because the following files don't have the correct license header:

> [INFO] --- license-maven-plugin:2.11:check (enforce-license-headers) @ css-custom-rules-plugin ---
> [INFO] Checking licenses...
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/MyCssCustomRulesDefinition.java
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/MyScssCustomRulesDefinition.java
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/checks/css/ForbiddenPropertiesCheck.java
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/MyLessCustomRulesDefinition.java
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/checks/css/ForbiddenUrlCheck.java
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/checks/less/InterpolatedPropertiesCheck.java
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/checks/scss/InterpolatedPropertiesCheck.java
> [WARNING] Missing header in: /home/travis/build/edwelker/sonar-css-plugin-copy/its/plugin/plugins/css-custom-rules-plugin/src/main/java/org/sonar/css/MyCssCustomRulesPlugin.java
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] SonarQube CSS / SCSS / Less Analyzer :: Integration Tests SUCCESS [  2.317 s]
> [INFO] SonarQube CSS / SCSS / Less Analyzer :: Integration Tests :: Plugin SUCCESS [  0.134 s]
> [INFO] SonarQube CSS / SCSS / Less Analyzer :: Integration Tests :: Plugin :: Plugins SUCCESS [  0.052 s]
> [INFO] SonarQube CSS / SCSS / Less Analyzer :: Integration Tests :: Plugin :: Plugins :: Custom Rules FAILURE [  0.927 s]
> [INFO] SonarQube CSS / SCSS / Less Analyzer :: Integration Tests :: Plugin :: Tests SKIPPED
> [INFO] SonarQube CSS / SCSS / Less Analyzer :: Integration Tests :: Ruling SKIPPED
> [INFO] SonarQube CSS / SCSS / Less Analyzer :: Integration Tests :: Ruling :: Tests SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 6.037 s
> [INFO] Finished at: 2017-09-27T15:23:18Z
> [INFO] Final Memory: 38M/729M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.mycila:license-maven-plugin:2.11:check (enforce-license-headers) on project css-custom-rules-plugin: Some files do not have the expected license header -> [Help 1]
> >
